language: node_js

node_js:
  - 6.6.0

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm install -g gulp

install:
  - npm install

script:
  - gulp ci:build
