language: node_js

node_js:
  - 6.9.0

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g yarn

install:
  - yarn install
  - yarn global add gulp

script:
  - gulp ci:build
